name: M002

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 djangoProject.wsgi:application
    volumes:
      - .:/code
      - /projects/github/M002/backend/static/:/code/static/
      - /projects/github/M002/backend/media_root/:/code/media_root/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
